### ISSUE TITLE
Build iOS App: Error: cordovaProject.projectConfig.getFileResources is not a function

### ISSUE THREAD

**Issue by cuihantao** [wordpress-clients/hybrid#353]
Greetings,

I'm build the iOS app for the first time. I followed the instruction but keeps getting the error message

`Error: cordovaProject.projectConfig.getFileResources is not a function`

I checked `cordova requirements` and it passed.

```
Requirements check results for ios:
Apple OS X: installed darwin
Xcode: installed 8.3.2
ios-deploy: installed 1.9.1
CocoaPods: installed
```

Any help is greatly appreciated!

**Comment by cuihantao** [comment]
```
Error: cordovaProject.projectConfig.getFileResources is not a function

npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/Cellar/node@6/6.10.3/bin/node" "/usr/local/bin/npm" "run" "ios"
npm ERR! node v6.10.3
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wordpress-hybrid-client@2.0.2 ios: `npm run dumpdev && cordova run ios --device`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wordpress-hybrid-client@2.0.2 ios script 'npm run dumpdev && cordova run ios --device'.
```

I tried node@8.0.0 and it didn't work either. 

I tried to build it inside Xcode, but it simply cannot find the Cordova header include path...

**Comment by luatdolphin** [comment]
I also get trouble, I don't know why!!!

**Comment by shprink** [comment]
Please use 2.0.3: https://github.com/wordpress-clients/hybrid/releases/tag/v2.0.3
