### ISSUE TITLE
Push notification not received

### ISSUE THREAD

**Issue by flachica** [wordpress-clients/hybrid#354]
I have an App in Android 6.0 Huawei P8 with EMUI 4.0.1 

When App is open the push notification is received
When App is in background the notification appear on status bar
If app is closed the notification isn't received

I read firebase documentation and this https://github.com/phonegap/phonegap-plugin-push/issues/494 and two post recommend me that wordpress push plugin send me priority=high. I rewrite pushplugin and send this request

But push is not received on my App

Can anyone help me? Thanks

It's related with: https://github.com/phonegap/phonegap-plugin-push/issues/707#issuecomment-309211376

**Comment by Prabhat36** [comment]
The notifications are not getting send on some devices like Xiaomi Samsung zenphone etc why? 
And that plugin push notification lite only sends notification on 1000 devices why ? 
My last question is im on push notification lite version 2.6 should i update plugin to 3.2 or not ? I dont wants trouble in my running notification devices after ipdating , is it safe or not
