### ISSUE TITLE
Youtube (and embed) videos won't play

### ISSUE THREAD

**Issue by machour** [wordpress-clients/hybrid#355]
Hi,

Same as #218 : I cannot play a video on the generated application.
The iframe is loaded, I see the video cover with the red "Play" button, but clicking it makes the video loads forever, before outputting a Youtube error "Une erreur s'est produite. Veuillez réessayer ultérieurement. (ID de lecture xxxxx)

Tested on your application, on the [TALK] Redux & Angular2 post from 11/11/16

**Comment by shprink** [comment]
Do you see any errors on your side? It used to work. Probably a Content-Security-Policy problem.

**Comment by shprink** [comment]
Does not work on my app (old build) but works on the latest version:

![image](https://user-images.githubusercontent.com/1388706/27232409-41bc78b0-52b6-11e7-9cc8-cea5d8e363ea.png)

**Comment by machour** [comment]
That's the weird thing I was looking into.

I think I developped the app back when the repo was at github.com/shprink/wordpress-hybrid-client

I've seen the switch to wordpress-clients/hybrid , so I just cloned that repo and tested, everything works as a charm, the video plays well.

You could consider closing, but a nice statement about this in README.md or other file, could save a lot trouble.

And thanks for looking into that so quick !

**Comment by shprink** [comment]
no problem ;)
