### ISSUE TITLE
Error - npm start

### ISSUE THREAD

**Issue by mbascolo** [wordpress-clients/hybrid#359]
Hello,
I have an error that I can not solve, I leave the screen printing, if someone can help me I thank them.

regards

![captura de pantalla_2017-06-24_00-22-29](https://user-images.githubusercontent.com/4184022/27505319-3c925bbc-5873-11e7-89f5-61d4f2b153e8.png)

**Comment by shprink** [comment]
the installation must have stopped at some point `config/config.cson` is expected to exist.

run this:

```
rm -fr node_modules/ && yarn
```

At the end of the installation there is a hook that creates `config/config.cson`. Make sure the installation runs correctly. If not reopen this ticket with the error message you will have.

Thanks

**Comment by mbascolo** [comment]
Hi shprink
![captura de pantalla_2017-06-25_20-46-26](https://user-images.githubusercontent.com/4184022/27520738-4a63091e-59e8-11e7-8eab-4cd1c81f296c.png)
, thanks for your response.
I've done what you tell me, I get a new error. I attach a screen print, I hope your answer. Thank you.

**Comment by shprink** [comment]
as I told you `config/config.cson` must exist. please check. The `postinstall` hook https://github.com/wordpress-clients/hybrid/blob/develop/package.json#L10 is making sure of that.

If you do not have it it means you installation was not successful... was it?

**Comment by mbascolo** [comment]
Thank you very much! I had to reinstall sass, and then it worked perfectly.
Thanks for your help, I would like to be able to make a donation and if there is the possibility of being able to request you budget for other projects.

Best regards

**Comment by shprink** [comment]
There is a link for donations on top of the readme file: https://github.com/wordpress-clients/hybrid#wordpress-hybrid-client

thanks very much!
