### ISSUE TITLE
using ionic material with no errors on local host but not working on device  

### ISSUE THREAD

**Issue by Prabhat36** [wordpress-clients/hybrid#362]
hello @shprink  i have successfully loaded ionic material into this app on localhots its works like charm everything is perfect no errors, but when i launch it on android device i get error saying  **"the connection to the server was unsuccessful. (file ///android_asset/www/index.html)"**  
i think the error is occurring because the **ionic.css, ionic.material.min.css, style.css and ionic.material.min.js** which i have loaded into index.html file,  
            screenshots of app localhost is attached,  
    
I hope you can help me about these problems. Thanks

**localhost with no error**
![screenshot from 2017-07-26 23-21-02](https://user-images.githubusercontent.com/14105960/28636156-e2e4fb7c-725a-11e7-88b4-173d90614f9b.png)

**my index.html file image**
![index](https://user-images.githubusercontent.com/14105960/28636266-4188cfd2-725b-11e7-94cf-367d6ed60815.png)

**Comment by shprink** [comment]
I have no clue I am sorry. I have never used that lib. As it is not an issue of this project I will close.

Let me know if you make it work.

**Comment by Prabhat36** [comment]
Ok thanks , i just need small help , can you please tell me how can i put my material scripts in head tag of index.html , because of the webpack plugin i have no idea that how you included all scripts in proper sequence, just give me one example how can i make it easy to place my own scripts in head section of index.html 
Hope you ll help me in this problem at least 
Thank you @shprink

**Comment by shprink** [comment]
You need to import it in you config index.js https://github.com/wordpress-clients/hybrid/blob/develop/dist/index.js:

```
import 'ionic-material/dist/js/ionic.material.min.js'
```

same for the CSS

**Comment by Prabhat36** [comment]
thank you @shprink  it worked, but only this file is not taking efferct **import 'ionic/release/css/ionic.css';**
should i need to  import ionic.css file into any another file ? please help 
Thank you @shprink
![js](https://user-images.githubusercontent.com/14105960/28744138-51cbb192-7478-11e7-9ed3-614c1162c028.png)

**Comment by shprink** [comment]
why do you need `ionic/release/css/ionic.css` ? Ionic CSS is already loaded in the app via Scss

**Comment by Prabhat36** [comment]
![image](https://user-images.githubusercontent.com/14105960/29026512-c0faad34-7b99-11e7-99dc-ab47ac31991f.png)

dumpprod stuks on 37% , can you help me with this? @shprink

**Comment by shprink** [comment]
not sure I can help on that. Try to rollback your changes (git stash) then try again
