### ISSUE TITLE
v3 - refresh items store at startup

### ISSUE THREAD

**Issue by VinceRafale** [wordpress-clients/hybrid#364]
Hi,
I know the v3 is still under development, but I would like to understand what would/will be the best way to refresh items(posts) in the ngrx store at startup? So that users can be shown the recent items as well.
I've thought of clearing the items store during startup, only if an internet connection is available , but maybe there is a more elegant way to do that?

What are your thoughts?
thanks

**Comment by shprink** [comment]
I think the plan is to display a button hover the list when something new is ready to be displayed (fetch on ngOnInit). The list would not be cleared unless the user clicks that button or pull to refresh for a better user experience.

What do you think?

**Comment by VinceRafale** [comment]
ok I see the point, yes could be a solution to display a button which acts the same way as a pull refresh, however I would prefer to opt for an automatic method, without any user intervention...

however I guess the same issue would arise when a push notification arrives for a new post, the user taps on the notification.. but when he comes back to the post lists, he wouldn't be able to find the new item in the list and is forced to click on the button. so you would need to find a way to clear the store at some point

**Comment by shprink** [comment]
Call the same method as the pull to refresh action.
