### ISSUE TITLE
Push being automaticly sent if a new WordPress Post goes online?

### ISSUE THREAD

**Issue by gnrmarcel** [wordpress-clients/hybrid#368]
I have a question, if a Push will be automaticly sent if a new WordPress Post goes online and the push on android or ios will be open the post in the app in the detail view?

**Comment by shprink** [comment]
it will open the app for now not the specific post. This part of code https://github.com/wordpress-clients/hybrid/blob/develop/lib/pushNotifications/service.js#L196-L208 does not work as it should. Won't fix for v2 but PRs are welcome
