### ISSUE TITLE
Unable to start the server with v2.0.3 - Please help

### ISSUE THREAD

**Issue by ajaykumarsoma** [wordpress-clients/hybrid#370]
I am trying to install and run WPHC. Unable to start the server. attached the log file. Kindly help.
**The OS details below.**
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

**The versions of node, npm, yarn given below.**
root@docker-512mb-blr1-01:~/wordpress-hybrid-client# node -v
v7.10.1
root@docker-512mb-blr1-01:~/wordpress-hybrid-client# npm -v
4.2.0
root@docker-512mb-blr1-01:~/wordpress-hybrid-client# yarn -v
yarn install v0.27.5

**The debug log is below.**
[2017-08-29T15_50_06_983Z-debug.txt](https://github.com/wordpress-clients/hybrid/files/1260890/2017-08-29T15_50_06_983Z-debug.txt)

**Comment by shprink** [comment]
Please re install: `rm -fr node_module && yarn`

**Comment by ajaykumarsoma** [comment]
Shprink,

I would like to thank you and express my gratitude for quick reply. I have done as suggested. But build still fails.
Then I deleted the repo and cloned it again. Even then same issue.

Kindly Help me fix this issue. Also I would like to create a docker image for quickly running WPHC. Would you please give your approval for the same?

[2017-09-01T05_52_19_930Z-debug.txt](https://github.com/wordpress-clients/hybrid/files/1269281/2017-09-01T05_52_19_930Z-debug.txt)

**Comment by shprink** [comment]
Not sure what's wrong with your setup. If you want to try with Docker this https://github.com/shprink/wphc-dockerbox worked at some point (long time ago) and might be a good start for you.
