### ISSUE TITLE
How to change color of empty featured image box

### ISSUE THREAD

**Issue by dardania84** [wordpress-clients/hybrid#372]
![img-2296](https://user-images.githubusercontent.com/5423235/29863893-0ca6d0ee-8d3f-11e7-837f-e93ef00f8907.PNG)

I would like to change the white color to something else. Please help.

Thank you...

**Comment by shprink** [comment]
It is just CSS. Open your devtools in Chrome and try to find the appropriate selector. Once you have it you can overwrite any CSS rules in `config/config.scss`

**Comment by dardania84** [comment]
Do i need to convert CSS to place it in config.scss or just paste the code the way it it is

**Comment by dardania84** [comment]
wphc-posts .card .item-image {
    height: 200px;
    background-color: #e42112;
    background-size: cover;
    position: relative;
}



This is the CSS

**Comment by dardania84** [comment]
never mind i got it 

thank you!
