### ISSUE TITLE
Way to link menu item to about.html template

### ISSUE THREAD

**Issue by twnaing** [wordpress-clients/hybrid#381]
I found the following in `template/index.js`

// $templateCache.put('module/about.html', require('!html!./module/about.html'));

but couldn't find anywhere in documentation to calling this template.

How can I link a menu item to the about.html ?

**Comment by ugurcandede** [comment]
closed

**Comment by ugurcandede** [comment]
close #381

**Comment by ugurcandede** [comment]
closed #381
