### ISSUE TITLE
minimize the apk size 

### ISSUE THREAD

**Issue by hasnankar** [wordpress-clients/hybrid#384]
with all default config and plugins , the app size is approx. 100 MB !!! ,how we can decrease this size maybe with exclude some libraries or something. what should i do ?

**Comment by Prabhat36** [comment]
Just remove crosswalk web view plugin, and the magic happens your app size will be max 10mb, 
Or if you need crosswalk in your app try to install crosswalk lite then 👍🏻

**Comment by shprink** [comment]
100MB is not possible. Last time I checked it was max 40MB with crosswalk (default). As @Prabhat36 mentionned removing crosswalk or using crosswalk lite will reduce the PAK size: https://github.com/wordpress-clients/hybrid/blob/c388e2c408bb7433e05b900931ff6319527690e3/BUILD.md#crosswalk
