### ISSUE TITLE
Author section

### ISSUE THREAD

**Issue by SBrendan** [wordpress-clients/hybrid#387]
Hi,

I have a problem with my api rest, when i'm try to get the user list, I have an error "You don't have permission to get the list" but in your issue #30 you say no need auth with api v2.

Thanks

**Comment by shprink** [comment]
Getting users does not require any permission : http://demo.wp-api.org/wp-json/wp/v2/users

Please share your API url.

**Comment by SBrendan** [comment]
https://stadion-actu.fr/wp-json/wp/v2/users

**Comment by SBrendan** [comment]
I have detected the problem, it's wp security plugins the problem. I'm search where is the option. Thk :)
