### ISSUE TITLE
Cannot find name 'require'. error

### ISSUE THREAD

**Issue by Isagani95** [wordpress-clients/hybrid#390]
Im having error after the installation.

please see the link below: 
https://ibb.co/inOcEb

thanks for quick reponse :)

**Comment by shprink** [comment]
I am guessing you are using the develop branch which is under dev and I still have no idea how it reacts on windows. 

If you want a production version use tags > v2 but it is not Ionic/Angular 2.

I am about to push a Dockerfile to be able to build and run the Prod app in a container. Maybe check that if you are interested

**Comment by XjSv** [comment]
Same exact issue here, running on Windows 7.

**Comment by shprink** [comment]
to be clear:

- v2 is not compatible with Windows. Docs: https://github.com/wordpress-clients/hybrid/blob/v2.0.3/README.md
- v3 should be compatible with Windows but still in alpha. Docs: https://wordpress-clients.gitbooks.io/pwa-hybrid/
